import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";

import AnnouncementBar from "~/components/banner";
import { Logo } from "~/components";

import Link from 'next/link'

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const Footer = () => {

  return (
    <div className='flex flex-col bg-black text-white pl-5 pr-5 pb-2 justify-center align-middle'>
      <div className='flex flex-row justify-center gap-5'>
        <div className='w-40 flex flex-row text-sm pl-20 pt-4'>
          <div className='flex flex-col gap-2 '> 
            <Link href='/search'>Search</Link>
            <Link href='/privacy'>Privacy</Link>
            <Link href='/terms'>Terms</Link>
            <Link href='/refunds'>Refunds</Link>
          </div>
         
        </div>
        <div className='w-40 flex flex-col gap-1 pt-2'>
          <div className='flex flex-row justify-start'>
            <Logo/>
          </div>
          
            <span className='text-xs'>Join our newsletter below.</span>
            <input className='placeholder:p-2 placeholder:bg-gray-400 placeholder:text-sm placeholder:text-slate-700' type='text' placeholder='Enter Email'/>
            <div>
              <button className=' bg-gray-600 px-2 py-1 text-sm h-6'>Subscribe</button>
            </div>
        </div>
      </div>
      <div className='text-[10px] text-center pt-8'>@2023 NextDev</div>
    </div>
  )
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <AnnouncementBar message="Early Black Friday: 35% Off For A Limited Time."   />

        <TRPCReactProvider cookies={cookies().toString()}>{children}</TRPCReactProvider>
        <Footer/>
      </body>
    </html>
  );
}
